.TH DWB 1 "August 2010" dwb
.SH NAME
dwb \- dynamic web browser
.SH SYNOPSIS
.B dwb
[ options ] [ <urls> ] 
.SH DESCRIPTION
dwb is a small webbrowser based on webkit and GTK which aimes to be mostly
keyboard-driven. 

.SH COMMAND LINE ARGUMENTS
.TP
.B \-p <profile>
Specify a profile.
.TP
.B \-r <sessionname>
Restore session <sessionname> or the default session, if sessionname is omitted.
.TP
.B \-n
New instance, overrides property "single-instance".
.TP
.B \-v
Show version information and exit.
.TP
.B <urls>
URLs loaded on startup.

.SH MODES
dwb has different modes:
.TP
.BR Normalmode
The default Mode. Pressing "Escape" will get you always back to
Normalmode.
.TP
.BR Insertmode 
Used for editing text-elements in a webpage. 
.TP
.BR Hintmode 
Follow links via hints. 


.SH Usage
Note: all shortcuts are casesensitive, e.g. C-H means Control-Shift-h.
.SS "Normalmode shortcuts:"
.TP
.BR [n]j
Scroll [n times] down (command: 
.BR scroll_down ).
.TP
.BR [n]k
Scroll [n times] up (command: 
.BR scroll_up ).
.TP
.BR [n]h
Scroll [n times] left (command: 
.BR scroll_left ).
.TP
.BR [n]l
Scroll [n times] right (command 
.BR scroll_right).
.TP
.BR  [n]C-f
Scroll [n] Pages down (command
.BR scroll_page_down ).
.TP
.BR [n]C-b
Scroll [n] Pages up (comman
.BR scroll_page_up  ).
.TP
.BR  [n]C-d
Scroll [n] half pages down (command
.BR scroll_halfpage_down ).
.TP
.BR [n]C-u
Scroll [n] half pages up (command
.BR scroll_halfpage_up  ).
.TP 
.BR [n]%
Scroll to [n] percent of the document (command
.BR scroll_percent ).
.TP
.B : 
Enter Commandmode.
.TP
.BR o 
Open new url in the focused view (command
.BR open ).
.BR go 
Open url in the focused view, set the current url in the navigation bar.
.TP
.BR O 
Open url in a new view (command 
.BR open_nv ).
.TP
.BR gO 
Open url in a new view, set the current url in the navigation bar.
.TP
.BR wo 
Open url in a new instance (command 
.BR open_nw ).
.TP
.BR wO 
Open url in a new window, set the current url in the navigation bar.
.TP
.BR i 
Enter Insertmode (command 
.BR insert_mode ).
.TP
.BR ga 
Add a new blank view (command
.BR add_view ).
.TP
.BR d
Close current view (command
.BR remove_view ).
.TP
.BR u
Undo closing last view (command
.BR undo ).
.TP
.BR gm 
Toggle Maximized Layout (command 
.BR toggle_maximized ).
.TP
.BR C-h
Open the default startpage (command
.BR open_start_page ).
.TP
.BR H  
Go back (command 
.BR history_back ).
.TP
.BR L 
Go forward (command 
.BR history_forward ).
.TP
.BR M
Add a bookmark (command
.BR bookmark ).
.TP 
.B gb
Show Bookmarks (command
.BR bookmarks ).
.TP 
.B gB
Show Bookmarks, open bookmark in a new view (command
.BR bookmarks_nv ).
.TP 
.B wB
Show Bookmarks, open bookmark in a new window (command
.BR bookmarks_nw ).
.TP
.BR m[:graph:] 
Add a quickmark (command 
.BR save_quickmark ).
.TP
.BR b[:graph:]
Open quickmark (command 
.BR open_quickmark ).
.TP
.BR B[:graph:]
Open quickmark in a new view (command
.BR open_quickmark_nv ).
.TP
.BR wb[:graph:]
Open quickmark in a new window (command
.BR open_quickmark_nw ).
.TP
.BR tb
Toggle layout Normalstack <-> Bottomstack (command
.BR toggle_bottomstack ).
.TP
.BR gl 
Enlarge masterarea (command 
.BR increase_master ). 
.TP
.BR gh 
Minimize masterarea (command 
.BR decrease_master ). 
.TP
.BR r
Reload focused view (command
.BR reload ).
.TP
.BR [n]zi
Zoom in [n times] (command
.BR zoom_in ). 
.TP
.BR [n]zo
Zoom out [n times] (command 
.BR zoom_out ). 
.TP
.BR z=
Zoom to 100% (command 
.BR zoom_normal ).
.TP
.BR sf
Save all configuration files (command
.BR save ).
.TP
.BR ZZ
Save current session and exit (command 
.BR save_session ).
.TP
.BR gZZ 
Save current session with name and exit (command 
.BR save_named_session ).
.TP
.BR gp
Push current View to master area (command
.BR push_master ).
.TP
.BR [n]J
Cycle focus [n views] forwards. (command 
.BR focus_next ).
.TP
.BR [n]K
Cycle focus [n views] backwards. (command 
.BR focus_prev ).
.TP
.BR [n]T
Focus nth view or first, if n is ommitted. 
.TP
.BR f 
Show hints (command 
.BR hint_mode ).
.TP
.BR F
Show hints, open link in a new view. (command
.BR hint_mode_nv ).
.TP
.BR wf
Show hints, open link in a new view. (command
.BR hint_mode_nw ).
.TP
.BR gd 
Download via hints (command 
.BR download_hint ).
.TP
.BR gi
Focus next textinput (command 
.BR focus_input ). 
.TP
.BR gf 
Toggle "view source" (command 
.BR view_source ). 
.TP
.BR CC 
Allow cookie for the current web-page. The domain will be saved in 
.IR cookies.allow
(command
.BR allow_cookie ).
.TP
.BR yy
Yank selected text or if no text is selected the current url to clipboard
(command 
.BR yank ).
.TP
.BR yY
Yank selected text or if no text is selected the current url to primary
selection (command 
.BR yank_primary ).
.TP
.BR pp
Paste from clipboard (command 
.BR paste ).
.TP
.BR pP
Paste from primary selection (command
.BR paste_primary ).
.TP
.BR Pp
Paste from clipboard and load in a new view (command 
.BR paste_nv ).
.TP
.BR PP
Paste from primary selection and load in a new view (command
.BR paste_primary_nv ). 
.TP
.BR wp
Paste from clipboard and load in a new window (command 
.BR paste_nw ).
.TP
.BR wP
Paste from primary selection and load in a new window (command
.BR paste_primary_nw ). 
.TP
.BR gs
Add a searchengine. Text fields can be focused via hints (command 
.BR save_search_field ).
.TP
.BR Ss 
Show global settings (command
.BR show_global_settings ).
.TP
.BR Sk 
Show keys (command
.BR show_keys ).
.TP
.BR ss 
Set setting (command
.BR set_setting ).
.TP
.BR sgs 
Set global setting (command
.BR set_global_setting ).
.TP
.BR sk
Set keyboard shortcut (command
.BR set_key ).
.TP
.BR C-p 
Toggle proxy (command
.BR proxy ).
.TP
.BR tsh
Toggle scripts for current host permanently (command
.BR toggle_scripts_host ).
.TP
.BR tsu
Toggle scripts for current url permanently (command
.BR toggle_scripts_uri ).
.TP
.BR tth
Toggle scripts for current host temporarily (command
.BR toggle_scripts_host_tmp ).
.TP
.BR ttu
Toggle scripts for current url temporarily (command
.BR toggle_scripts_uri_tmp ).
.TP
.BR V
Next navigation action will be opened in a new view.
.TP
.BR W
Next navigation action will be opened in a new window.
.TP
.BR eu
Show userscripts (command 
.BR execute_userscript ).
.TP 
.BR wi
Show the webinspector. Note that 'enable-developer-extras' has to be set. 
.TP 
.BR C-M-p
Print focused frame.
.TP
.BR unbound 
Toggle autoload images (command 
.BR autoload_images ).
.TP
.BR unbound 
Toggle autoresize window (command 
.BR autoresize_window ).
.TP
.BR unbound 
Toggle autoshrink images (command 
.BR autoshrink_images ).
.TP
.BR unbound 
Toggle caret browsing (command 
.BR caret_browsing ).
.TP
.BR unbound 
Toggle java applets (command 
.BR java_applets ).
.TP
.BR unbound 
Toggle plugins (command 
.BR plugins ).
.TP
.BR unbound 
Toggle private browsing (command 
.BR private_browsing ).
.TP
.BR unbound 
Toggle scripts (command 
.BR scripts ).
.TP
.BR unbound 
Toggle spell checking (command 
.BR spell_checking ).
.TP
.BR unbound 
Load a html string. This command is mainly intended for use in userscripts (command 
.BR load_html ).
.TP
.BR unbound 
Load a html string in a new view. This command is mainly intended for use in userscripts (command 
.BR load_html_nv ).
.TP 
.B Tab (S-Tab) 
In Normal mode Tab shows the next (previous) shortcut, that matches the
currently entered keysequence. 
When opening a url, the next (previous) item in command
history, bookmarks or history will be completed. In Hintmode the next (previous)
hint will get focus. Tab also completes settings and shortcut-settings. 
When initiating a download, full paths (downloads and spawning programs) and
binaries (spawning programs) in PATH will be completed. 

.SS "Textentry shortcuts"
.TP
.BR C-h
Delete a single letter.
.TP
.BR C-w
Delete previous word.
.TP
.BR C-u
Delete to the beginning of the entry.
.TP
.BR C-f
Move cursor one word forward.
.TP
.BR C-b
Move cursor one word back.
.TP
.BR C-j
Show next item in command history.
.TP
.BR C-k
Show previous item in command history.
.TP
.BR C-x
When initalizing a download, C-x toggles between choosing a file path and
choosing a spawning application.
.TP
.BR C-p
Init local path completion.
.TP
.BR C-H
Init history completion. 
.TP
.BR C-B
Init bookmark completion. 
.TP
.BR C-I
Init input history completion. 
.TP
.BR C-S
Init searchengine completion.
.TP
.BR C-U
Init userscript completion.

.SH CUSTOMIZATION
dwb can be  customized in a web interface (command 
.BR show_settings/show_global_settings ) 
or via command line (command
.BR set_setting/set_global_setting ). 
The non global commands only affect the
currently focused view, the global commands affect all views. Modified settings
will be saved in 
.IR ~/.config/dwb/settings 
when closing dwb. 
Shorcuts can also be modified in a web interface (command 
.BR show_keys ) 
or via command line (command 
.BR set_key ). 
Shortcuts will be saved in 
.IR ~/.config/dwb/keys .

.SS Per-view-settings
Per-view-settings only affect the focused view. All per-view-settings can also
be set globally and then will affect all views. If a string value is set to 
.IR NULL
the default value will be used. The settings in detail are: 
.TP
.BR adblocker
Block advertisements using a filterlist. The filter can be specified in
.IR $XDG_CONFIG_HOME/dwb/adblock .
Regular expressions can be used by putting a '@' at the beginning of the line. 
default value:
.IR false .
.TP
.BR auto-load-images  
Load images automatically. Possible values: true/false, 
default value:
.IR true .
.TP
.BR auto-resize-window
Resize window through DOM-methods. Possible values: true/false, 
default value:
.IR false .
.TP
.BR auto-shrink-images
Automatically shrink standalone images to fit. Possible values: true/false, 
default value:
.IR true .
.TP
.BR cursive-font-family
Default cursive font family used to display text. Possible values: a font description or 
NULL, 
default value:
.IR NULL .
.TP
.BR custom-encoding
A custom encoding used for the webview. Possible values: encoding string or 
NULL,
default value:
.IR NULL .
.TP
.BR default-encoding
The default encoding used to display text. Possible values: encoding string or 
NULL,
default value:
.IR NULL .
.TP
.BR default-font-family
The default font family used to display text. Possible values: a font
description or
NULL, 
default value:
.IR sans-serif .
.TP
.BR default-font-size
The default font size used to display text. Possible values: a font size
(integer),
default value:
.IR 12 .
.TP
.BR default-monospace-font-size
The default font size used to display monospace text. Possible values: a font size
(integer),
default value:
.IR 10 .
.TP
.BR editable
Whether the content of a webpage should be editable. Possible values:
true/false,
default value:
.IR false .
.TP
.BR enable-caret-browsing
Whether to enable caret browsing. Possible values: true/false,
default value:
.IR false .
.TP
.BR enable-default-context-menu
Whether right-clicks open a context menu. Possible values: true/false,
default value:
.IR false .
.TP
.BR enable-dns-prefetching
Whether webkit prefetches domain names. 
default value:
.IR true .
.TP
.BR enable-developer-extras
Whether the web-inspector should be enabled. Possible values: true/false,
default value:
.IR false .
.TP
.BR enable-dom-paste
Whether enable DOM-paste. Possible values: true/false,
default value:
.IR false .
.TP
.BR enable-frame-flattening
Whether to enable the Frame Flattening. With this setting each subframe is expanded
to its contents, which will flatten all the frames to become one scrollable page.
Whether file uris can be accessed. Possible values: true/false, 
default value:
.IR false .
.TP
.BR enable-file-access-from-file-uris
Whether file uris can be accessed. Possible values: true/false, 
default value:
.IR true .
.TP
.BR enable-html5-database
Whether to enable HTML5 client-side SQL database support.
Possible values: true/false,
default value:
.IR true .
.TP
.BR enable-html5-local-storage
Whether to enable HTML5 localStorage support.
Possible values: true/false,
default value:
.IR true .
.TP
.BR enable-java-applet
Whether to enable Java <applet>-tag.
Possible values: true/false,
default value:
.IR true .
.TP
.BR enable-offline-web-application-cache
Enable or disable HTML5 offline web application cache support.
Possible values: true/false,
default value:
.IR true .
.TP
.BR enable-page-cache
Enable or disable page cache.
Possible values: true/false,
default value:
.IR false .
.TP
.BR enable-plugins
Enable or disable embedded plugins.
Possible values: true/false, 
default value:
.IR true .
.TP
.BR enable-private-browsing
Enable or disable private browsing. If set globally, the sessions history will
not be saved.
Possible values: true/false, 
default value:
.IR false .
.TP
.BR enable-scripts
Enable or disable embedded scripting-languages.
Possible values: true/false,
default value:
.IR true .
.TP
.BR enable-site-specific-quirks
Enables the site-specific compatibility workarounds.
Possible values: true/false,
default value:
.IR false .
.TP
.BR enable-spatial-navigation
Whether to enable the Spatial Navigation. This feature consists in the ability
to navigate between focusable elements in a Web page, such as hyperlinks and
form controls, by using Left, Right, Up and Down arrow keys.
Possible values: true/false,
default value:
.IR false .
.TP
.BR enable-spell-checking
Whether to enable spell checking.
Possible values: true/false,
default value:
.IR false .
.TP
.BR enable-universal-access-from-file-uris
Whether to allow files loaded through file:// URIs universal access to all pages.
Possible values: true/false,
default value:
.IR true .
.TP
.BR enable-xss-auditor
Whether to enable the XSS Auditor. This feature filters some kinds of reflective
XSS attacks on vulnerable web sites.
Possible values: true/false,
default value:
.IR true .
.TP
.BR enforce-96-dpi
Enforce a resolution of 96 DPI.
Possible values: true/false,
default value:
.IR false .
.TP
.BR fantasy-font-family
Default fantasy font family used to display text. Possible values: a font description or 
NULL,
default value:
.IR serif .
.TP
.BR javascript-can-access-clipboard
Whether javascript can access Clipboard.
Possible values: true/false,
default value:
.IR false .
.TP
.BR full-content-zoom
Whether the full content is scaled when zooming.
Possible values: true/false,
default value:
.IR false .
.TP
.BR javascript-can-open-windows-automatically
Whether JavaScript can open popup windows automatically without user intervention.
Possible values: true/false,
default value:
.IR false .
.TP
.BR minimum-font-size
The minimum font size used to display text. Possible values: a font size
(integer),
default value:
.IR 5 .
.TP
.BR minimum-logical-font-size
The minimum logical font size used to display text. Possible values: a font size
(integer),
default value:
.IR 5 .
.TP
.BR monospace-font-family
Default font family used to display monospace text. Possible values: a font description or 
NULL,
default value:
.IR monospace .
.TP
.BR print-backgrounds
Whether background images should be printed. 
Possible values: true/false,
default value:
.IR true .
.TP
.BR resizable-text-areas
Whether text areas are resizable.
Possible values: true/false,
default value:
.IR true .
.TP
.BR sans-serif-font-family
Default sans-serif font family used to display text. Possible values: a font description or 
NULL,
default value:
.IR sans-serif .
.TP
.BR serif-font-family
Default serif font family used to display text. Possible values: a font description or 
NULL,
default value:
.IR serif .
.TP
.BR spell-checking-language
The languages to be used for spell checking, separated by commas. Possible
values: a string or 
NULL,
default value:
.IR NULL .
.TP
.BR tab-cycles-through-elements
Whether the tab key cycles through elements on the page.
Possible values: true/false,
default value:
.IR true .
.TP
.BR user-agent
The user-agent-string. Possible values: a user-agent or 
NULL,
default value:
.IR NULL .
.TP
.BR user-stylesheet-uri
The URI of a stylesheet that is applied to every page. If a local file is used,
must start with file://. Possible values: an
uri-string or NULL,
default value:
.IR NULL .
.TP
.BR zoom-level
The zoom level of the content. Possible values: a decimal,
default value:
.IR 1.0 .
.TP
.BR zoom-step
The value by which the zoom level is changed when zooming in or out. Possible
values: a decimal,
default value:
.IR 0.1 .

.SS Global Settings
Global settings will affect all views. All per-view-settings can also be set
globally, see 
.BR per-view-settings 
for details. Settings, that only can be set globally are: 
.TP 
.BR active-completion-bg-color
The background color for an active element in tab-completion. Possible values:
an rgb color-string,
default value:
.IR #000000 .
.TP 
.BR active-completion-fg-color
The foreground color for an active element in tab-completion. Possible values:
an rgb color-string.
default value:
.IR #53868b .
.TP 
.BR active-bg-color
The background color of the focused view. Possible values: an rgb color-string,
default value:
.IR #000000 .
.TP 
.TP 
.BR active-fg-color
The foreground color of the focused view. Possible values: an rgb color-string.
default value:
.IR #ffffff .
.TP 
.BR auto-completion
Whether possible keystrokes should be shown. (Shift-) Tab cycles through keystrokes.
Possible values: true/false,
default value:
.IR true .
.TP 
.BR background-tabs
Open new views in background. 
Possible values: true/false,
default value:
.IR false .
.TP 
.BR complete-bookmarks
Whether to complete bookmarks with tab-completion. Possible values: true/false,
default value:
.IR true .
.TP 
.BR complete-commands
Whether to complete input history with tab-completion. Possible values:
true/false,
default value:
.IR true .
.TP 
.BR complete-history
Whether to complete browsing history with tab-completion. Possible values:
true/false,
default value:
.IR true .
.TP 
.BR complete-searchengines
Whether to complete searchengines with tab-completion. Possible values:
true/false,
default value:
.IR false .
.TP 
.BR complete-userscripts
Whether to complete userscripts with tab-completion. Possible values:
true/false,
default value:
.IR false .
.TP 
.BR cookies
Whether to allow all cookies. Possible values: true/false,
default value:
.IR false .
.TP 
.TP 
.BR default-width
The default width of dwb's window. Possible values: width in pixel,
default value:
.IR 800 .
.TP 
.BR default-height
The default height of dwb's window. Possible values: height in pixel,
default value:
.IR 600 .
.TP 
.BR download-external-command
A command that will be invoked if 'download-use-external-program' is set. There
are four variables that can be used in the command: 
.IR dwb_uri
will be replaced with the download-uri, 
.IR dwb_output
will be replaced with the fullpath of the destination, 
.IR dwb_cookies
will be replaced with the path to the cookie-file,
.IR dwb_fifo
will be replaced with the fifo-path if "use-fifo" is enabled,
default value:
.IR xterm\ -e\ wget\ 'dwb_uri'\ -O\ 'dwb_output'\ --load-cookies\ 'dwb_cookies' .
.TP
.BR download-use-external-program
Whether to use an external download programm specified in
\'download-external-programm\' or the builtin download helper.
Possible values: true/false,
default value:
.IR true .
.TP 
.BR error-color
The color for error-messages. Possible values: an rgb color-string,
default value:
.IR #ff0000 .
.TP 
.BR factor
The zoom level of stacked views. Possible values: zoom level (decimal),
default value:
.IR 0.3 .
.TP 
.BR font
The font used for the ui. Possible values: a font description
string,
default value:
.I monospace 8.
.TP 
.BR font-completion
The font used for tabcompletion. Possible values: a font description
string,
default value: 
.TP 
.BR font-entry
The font used for the address bar. Possible values: a font description
string,
default value: 
.TP 
.BR font-inactive
The font used for inactive views. Possible values: a font description
string,
default value: 
.TP 
.BR ftp-client
Program to open ftp://. 
.IR dwb_uri
will be replaced with the ftp-url. Default value: 
.IR xterm\ -e\ ncftp\ 'dwb_uri' .
.TP 
.BR hide-tabbar
Hide the tabbar. Possible values: always, never, tiled. 
default value:
.IR never
.TP 
.BR hint-active-color
The background color for active link, i.e. the link followed when Return is
pressed. Possible values: a rgb color string,
default value:
.IR #00ff00 .
.TP 
.BR hint-bg-color
The background color used for hints. Possible values: a rgb color string,
default value:
.IR #000088 .
.TP 
.BR hint-border
The boreder used for hints. Possible values: a css border description,
default value:
.IR 2px\ dashed\ #000000 .
.TP 
.BR hint-fg-color
The foreground color used for hints. Possible values: a rgb color string,
default value:
.IR #ffffff .
.TP 
.BR hint-font-family
The font family used for hints. Possible values: css font family description,
default value:
.IR monospace .
.TP 
.BR hint-font-size
The font size used for hints. Possible values: css font size description,
default value:
.IR 12px .
.TP 
.BR hint-font-weight
The font wheight used for hints. Possible values: css font weight description,
default value:
.IR normal .
.TP 
.BR hint-letter-seq
A letter sequence used for letter hints. Possible values: a letter sequence,
every letter should appear only once.
Default value:
.IR FDSARTGBVECWXQYIOPMNHZULKJ .
.TP 
.BR hint-normal-color
The background color for a normal link. Possible values: a rgb color string,
default value:
.IR #ffff99 .
.TP 
.BR hint-opacity
The opacity of a hint. Possible values: a decimal from 0.0 to 1.0, 
default value:
.IR 0.75 .
.TP 
.BR hint-style
The type of hints, that are used. When set to "number", letters will match the
links text. Possible values: letter/number,
default value:
.IR letter .
.TP 
.BR history-length
The urls that are saved in the browsing history. Specifying a too large value
can make tab-completion slow. Possible values: number of urls,
default value:
.IR 500 .
.TP 
.BR insertmode-bg-color
The background color of the statusbar in insertmode. Possible values: an rgb
color-string,
default value:
.IR #dddddd .
.TP 
.BR insertmode-fg-color
The foreground color of the statusbar in insertmode. Possible values: an rgb
color-string,
default value:
.IR #000000 .
.TP 
.BR layout
The default layout. Possible values: Normal / Normal Maximized / Bottomstack /
Bottomstack Maximized / Maximized (same as Normal Maximized),
default value:
.IR Normal\ Maximized .
.TP
.BR mail-client
The email program that is used for mailto:-urls. 
.IR dwb_uri
will be replaced with the mail-url. Default value: 
.IR xterm\ -e\ mutt\ 'dwb_uri'.
.TP 
.BR message-delay
The duration messages are shown. Possible values: duration in seconds (integer),
default value:
.IR 2 .
.TP 
.BR normal-completion-bg-color
The background color of inactive element in tab-completion. Possible values: an
rgb color-string,
default value:
.IR #151515 .
.TP 
.BR normal-completion-fg-color
The foreground color of inactive element in tab-completion. Possible values: an rgb color-string.
color-string,
default value:
.IR #eeeeee .
.TP 
.BR normal-bg-color
The background color of a not focused view. Possible values: an rgb
color-string,
default value:
.IR #505050 .
.TP 
.BR normal-fg-color
The foreground color of a not focused view. Possible values: an rgb
color-string,
default value:
.IR #cccccc .
.TP 
.BR proxy
Whether to use a HTTP-proxy. Possible values: true/false,
default value:
.IR false .
.TP 
.BR proxy-url
The proxy-url, can also be set via the http_proxy environment variable. Possible
values: an url string,
default value:
.IR NULL .
.TP 
.BR save-session
Save the session when dwb is closed and restore the last saved session when
invoking dwb. Possible values: true/false,
default value:
.IR false .
.TP 
.BR scroll-step
The step-increment in pixels for scrolling. If set to a value lower or equal 0,
the default step-increment will be used.
default value: 
.IR 0.0 .
.TP 
.BR settings-bg-color
The background color of a the settings view. Possible values: an rgb
color-string,
default value:
.IR #151515 .
.TP 
.BR settings-border
The border for used for seperating lines in the settings view. Possible values: A
css-border-description,
default value:
.IR 1px\ dotted\ black .
.TP 
.BR settings-fg-color
The foreground color of a the settings view. Possible values: an rgb
color-string,
default value:
.IR #ffffff .
.TP 
.BR single-instance
Only one instance of dwb per user. This option will be overridden by the
commandlineoption -n. Possible values: true/false,
default value:
.IR false .
.TP 
.BR size
The size of the stacked area. Possible values: size in percent (integer),
default value:
.IR 30 .
.TP 
.BR ssl-trusted-color
Color of the url in the statusbar for ssl-encrypted sites and trusted
certificate.
default value:
.IR #00ff00 .
.TP 
.BR ssl-untrusted-color
Color of the url in the statusbar for ssl-encrypted sites and untrusted
certificate.
default value:
.IR #ff0000 .
.TP 
.BR startpage
The default startpage. Possible values: an url or "about:blank" for an empty
startpage,
default value:
.IR about:blank .
.TP 
.BR tab-active-bg-color
The background color the tab of the focused view. Possible values: an rgb
color-string,
default value:
.IR #000000 .
.TP 
.BR tab-active-fg-color
The foreground color of the tab of the focused view. Possible values: an rgb
color-string,
default value:
.IR #ffffff .
.TP 
.BR tab-normal-bg-color
The background color the tab of a not focused view. Possible values: an rgb
color-string,
default value:
.IR #505050 .
.TP 
.BR tab-normal-fg-color
The foreground color of the tab of a not focused view. Possible values: an rgb
color-string,
default value:
.IR #cccccc .
.TP 
.BR tabbed-browsing
Enable tabbed-browsing. If disabled, all new window/new tab requests will be
opened in a new window. 
default value:
.IR true .
.TP 
.BR use-fifo
Use a fifo to communicate with dwb, e.g. sending "open <url>" to the fifo would
load the url in the current view,
default value:
.IR false .

.SH FILES
.SS Scripts
Javascript userscripts can be stored in 
.IR ~/.config/dwb/scripts .
.SS Userscripts
Userscripts can be stored in 
.IR ~/.config/dwb/userscripts .
The first argument of the script will be the current url, the second argument is
the profile. The keybinding for
the script must be defined in the script itself in a commented line of the form
.B <comment symbols> dwb: <keybinding>.
Commands can be executed by sending the command to stdout.

.SS Examples
The following script will download the actual webpage:
.IP
#!/bin/bash
.PD 0
.IP 
# dwb: Control w

wget $1

.P
Popup an alert dialog:
.IP
#!/bin/bash
.PD 0
.IP 
# dwb: Control h

echo "open javascript:window.alert(\\"Hello world\\")"


.SH AUTHOR
Stefan Bolte <portix@gmx.net>
