#!/bin/bash 
# dwb: control y
# 
# Control the youtube player from command line
# Arguments: 
# p: play
# P: play
# m: toggle mute
# s: stop
# f<n>: seek to <n> seconds 
# v<0-100>: set volume to <0-100>% 
# q: Toggle highest resolution <-> default resolution
# default: pause the video and open it with VIDEOPLAYER

uri=$1
profile=$2
nummod=$3
arg=$4
VIDEOPLAYER=mplayer

run() {
  for pid in $(pgrep dwb); do 
    for name in /proc/${pid}/fd/*; do 
      if readlink "${name}" | grep Flash; then 
        ${VIDEOPLAYER} ${name} &>/dev/null & 
        break;
      fi
    done
  done 
  echo "close"
}
[[ ! $uri =~ .*\.youtube\..* ]] &&  exit 1

echo "open javascript:var p=document.getElementById('movie_player')"
case $arg in 
  p) echo -e "open javascript:if(p){ p.playVideo(); }\nclose\n" ;; 
  P) echo -e "open javascript:if(p){ p.pauseVideo(); }\nclose\n" ;; 
  s) echo -e "open javascript:if(p){ p.stopVideo(); }\nclose\n" ;;
  f*) echo -e "open javascript:if(p){ p.seekTo(${arg#f}, false);}\nclose\n" ;;
  v*) echo -e "open javascript:if(p){ p.setVolume(${arg#v});}\nclose\n" ;;
  m) echo -e "open javascript:if(p){ if (p.isMuted()) p.unMute(); else p.mute() }\nclose\n" ;;
  q) echo -e "open javascript:if(p){ var l=p.getAvailableQualityLevels(); if (p.getPlaybackQuality() == l[0]) p.setPlaybackQuality('default'); else p.setPlaybackQuality(l[0]); }\nclose\n" ;;
  *) echo -e "open javascript:if(p){ p.seekTo(0, false);;p.pauseVideo(); }"; run & ;;
esac

#vim: set tw=0
